package com.application.zimplyshop.extras;

public interface ObjectTypes {

    int OBJECT_TYPE_HOME_OBJECT = 1;
    int OBJECT_TYPE_ARTICLE_LIST_OBJECT = 2;
    int OBJECT_TYPE_PHOTO_LIST_OBJECT = 3;
    int OBJECT_TYPE_PRODUCT_LIST_OBJECT = 4;
    int OBJECT_TYPE_SHOP_CATEGORY_OBJECT = 5;
    int OBJECT_TYPE_SHOP_SUB_CATEGORY_OBJECT = 6;
    int OBJECT_TYPE_EXPERT_LIST_OBJECT = 7;
    int OBJECT_TYPE_COMPLETE_CATEGORY_LIST = 8;
    int OBJECT_TYPE_ARTICLE_PHOTO_CATEGORY_LIST = 9;
    int OBJECT_TYPE_ARTICLE_DETAIL = 10;

    int OBJECT_TYPE_SIGNUP = 11;

    int OBJECT_TYPE_CITY_LIST = 12;
    int OBJECT_TYPE_RESPONSE_FILTER = 13;

    int OBJECT_TYPE_MARKED_FAV = 14;
    int OBJECT_TYPE_MARKED_UNFAV = 15;
    int OBJECT_TYPE_FAV_LIST = 16;
    int OBJECT_TYPE_FORGOT_PASSWORD = 17;
    int OBJECT_TYPE_GCM_PUSH = 18;
    int OBJECT_TYPE_QUERY_RESPONSE_FILTER = 19;
    int OBJECT_TYPE_HOME_PHOTO = 20;
    int OBJECT_TYPE_REGIONLIST = 21;
    int OBJECT_TYPE_CATEGORY_OBJECT = 22;
    int OBJECT_TYPE_PRODUCT_CATEGORY = 23;
    int OBJECT_TYPE_SEARCHED_PRODUCTS = 24;
    int OBJECT_TYPE_PRODUCT_DETAIL = 25;
    int OBJECT_TYPE_ORDER_LIST = 26;
    int OBJECT_TYPE_SAVE_LIST = 27;
    int OBJECT_TYPE_GET_ADDRESSES = 28;
    int OBJECT_ADD_TO_CART = 29;
    int OBJECT_TYPE_CART = 30;
    int OBJECT_TYPE_CHECK_PINCODE = 31;
    int OBJECT_TYPE_ITEM_REMOVED = 32;
    int OBJECT_USER_DETAILS = 33;
    String OBJECT_TYPE_NONLOGGED_IN_CART = "nonloggedincartobj";
    int OBJECT_TYPE_SEARCHED_EXPERTS = 34;
    int OBJECT_TYPE_APPCONFIG = 35;
    int OBJECT_TYPE_FILTER_PRODUCTS = 36;
    int OBJECT_TYPE_PLACE_ORDER = 37;
    int OBJECT_TYPE_APPCONFIG_2 = 38;
    int OBJECT_TYPE_CANCEL_ORDER = 39;
    int OBJECT_TYPE_PRODUCT_SEARCH_RESULT = 40;
    int OBJECT_TYPE_PRODUCT_WISHLIST = 41;
    int OBJECT_TYPE_BANNER_OBJECT=42;
    int OBJECT_TYPE_MARK_PRODUCT_REVIEW = 43;
    int OBJECT_TYPE_REMOVE_PRODUCT_REVIEW = 44;
    int OBJECT_TYPE_ALL_BOOKED_PRODUCTS = 45;
    int OBJECT_TYPE_PHONE_VERIFICATION = 46;
    int OBJECT_TYPE_PHONE_VERIFICATION_INPUT = 47;
    int OBJECT_TYPE_PHONE_VERIFICATION_OTP = 48;
    int OBJECT_TYPE_NOTIFICATION_LIST_OBJ = 49;
}
